# Generated by Django 2.0.6 on 2018-06-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSpeedoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
