# Generated by Django 2.0.6 on 2018-07-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSpeedoAPI', '0002_key_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
